export const RAYDIUM_MAINNET_PROGRAMS = {
  CPMM: 'CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C',
  AMMV4: '675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8',
  CLMM: 'CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK',
};

export const RAYDIUM_DEVNET_PROGRAMS = {
  CPMM: 'DRaycpLY18LhpbydsBWbVJtxpNv9oXPgjRSfpF2bWpYb',
  AMMV4: 'DRaya7Kj3aMWQSy19kSjvmuwq9docCHofyP9kanQGaav',
  CLMM: 'DRayAUgENGQBKVaX8owNhgzkEDyoHTGVEGHVJT1E9pfH',
};

